# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hahaha/riscv/aquila_soc_0901/aquila_soc.cache/wt [current_project]
set_property parent.project_path /home/hahaha/riscv/aquila_soc_0901/aquila_soc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.5 [current_project]
set_property ip_repo_paths /home/hahaha/riscv/aquila_soc_0901/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /home/hahaha/riscv/aquila_soc_0901/aquila_soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/hdl/aquila_soc_wrapper.v
add_files /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/aquila_soc.bd
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_mig_7series_0_0/aquila_soc_mig_7series_0_0/user_design/constraints/aquila_soc_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_mig_7series_0_0/aquila_soc_mig_7series_0_0/user_design/constraints/aquila_soc_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_mig_7series_0_0/aquila_soc_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_axi_uartlite_0_0/aquila_soc_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_axi_uartlite_0_0/aquila_soc_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_axi_uartlite_0_0/aquila_soc_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_1/bd_bb3d_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_1/bd_bb3d_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_2/bd_bb3d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_2/bd_bb3d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_3/bd_bb3d_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_3/bd_bb3d_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_4/bd_bb3d_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_5/bd_bb3d_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_6/bd_bb3d_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_7/bd_bb3d_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_8/bd_bb3d_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_12/bd_bb3d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_13/bd_bb3d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_14/bd_bb3d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_15/bd_bb3d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_16/bd_bb3d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_17/bd_bb3d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_21/bd_bb3d_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_22/bd_bb3d_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_23/bd_bb3d_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_24/bd_bb3d_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_25/bd_bb3d_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_26/bd_bb3d_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_27/bd_bb3d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_28/bd_bb3d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_29/bd_bb3d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_30/bd_bb3d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_31/bd_bb3d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/bd_0/ip/ip_32/bd_bb3d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_rst_mig_7series_0_200M_0/aquila_soc_rst_mig_7series_0_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_rst_mig_7series_0_200M_0/aquila_soc_rst_mig_7series_0_200M_0.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/ip/aquila_soc_rst_mig_7series_0_200M_0/aquila_soc_rst_mig_7series_0_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/sources_1/bd/aquila_soc/aquila_soc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/constrs_1/new/aquila_soc_wrapper.xdc
set_property used_in_implementation false [get_files /home/hahaha/riscv/aquila_soc_0901/aquila_soc.srcs/constrs_1/new/aquila_soc_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top aquila_soc_wrapper -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef aquila_soc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file aquila_soc_wrapper_utilization_synth.rpt -pb aquila_soc_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
