# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/aquila_soc_wrapper.xdc

# Block Designs: bd/aquila_soc/aquila_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aquila_soc || ORIG_REF_NAME==aquila_soc} -quiet] -quiet

# IP: bd/aquila_soc/ip/aquila_soc_mig_7series_0_0/aquila_soc_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aquila_soc_mig_7series_0_0 || ORIG_REF_NAME==aquila_soc_mig_7series_0_0} -quiet] -quiet

# IP: bd/aquila_soc/ip/aquila_soc_axi_uartlite_0_0/aquila_soc_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aquila_soc_axi_uartlite_0_0 || ORIG_REF_NAME==aquila_soc_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/aquila_soc/ip/aquila_soc_smartconnect_0_0/aquila_soc_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aquila_soc_smartconnect_0_0 || ORIG_REF_NAME==aquila_soc_smartconnect_0_0} -quiet] -quiet

# IP: bd/aquila_soc/ip/aquila_soc_rst_mig_7series_0_200M_0/aquila_soc_rst_mig_7series_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aquila_soc_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==aquila_soc_rst_mig_7series_0_200M_0} -quiet] -quiet

# IP: bd/aquila_soc/ip/aquila_soc_aquila_0_1/aquila_soc_aquila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aquila_soc_aquila_0_1 || ORIG_REF_NAME==aquila_soc_aquila_0_1} -quiet] -quiet

# XDC: bd/aquila_soc/aquila_soc_ooc.xdc
